---
title: "ling460_model"
output: html_document
---

```{r, warning=FALSE}
# loading libraries
library(readr)
library(stringr)
library(tidyverse)
library(dplyr)
library(car)
library(stargazer)
```

```{r}
# reading in the data 
data <- read_csv("final_dataset/Data/output/income_mortality_aqi.csv")
```

```{r}
# filtering for the model 
data <- data %>%
  select(-c(FIPS, subregion, STATE_FIPS, State, County, County, CNTY_FIPS))

# cleaning the rank column to only include the state's ranking
data$Rank.within.US <- data$Rank.within.US %>%
  str_extract("\\d+") %>%
  as.numeric()
  
# creating first model 
full <- lm(Deaths ~ region + Good.Days + Moderate.Days + Unhealthy.for.Sensitive.Groups.Days + Unhealthy.Days + Very.Unhealthy.Days + Hazardous.Days + Median.AQI + Days.CO + Days.NO2 + Days.Ozone + Days.PM2.5 + Value..Dollars., data = data)
summary(full)
# statistically significant variables are moderate days, unhealthy for sensitive group days, very unhealthy days, hazardous days and median income

# checking for multicollinearity 
car::vif(full)
# looks like region is colinear and so is median AQI and days ozone

# creating a second model looking at region types as well - borrowed Bhargavi's code for the geo regions
west = c("California", "Colorado", "Nevada", "Hawaii", "Alaska", "Oregon", "Utah", "Idaho", "Montana", "Wyoming", "Washington")
midwest = c("Minnesota", "Wisconsin", "Illinois", "Indiana", "Ohio", "Michigan", "Missouri", "Iowa", "Kansas", "Nebraska", "North Dakota", "South Dakota")
southwest = c("New Mexico", "Arizona", "Oklahoma", "Texas")
southeast = c("Georgia", "North Carolina", "South Carolina", "Virginia", "West Virginia", "Kentucky", "Tennessee", "Mississippi", "Alabama", "Delaware", "Maryland", "Florida", "Louisiana", "Arkansas")
northeast = c("Massachusetts", "Rhode Island", "Connecticut", "Vermont", "New Hampshire", "Maine", "Pennsylvania", "New Jersey", "New York")
# first, adding a region column to the data 
data <- data %>% 
  mutate(geo = 
  case_when(region %in% west ~ "W",
            region %in% midwest ~ "MW",
            region %in% southwest ~ "SW",
            region %in% southeast ~ "SE",
            region %in% northeast ~ "NE")
  )

# now creating second model including region in the model 
# first taking out the NAs 
data <- data %>%
  na.omit()
mod2 <- lm(Deaths ~ Good.Days + Moderate.Days + Unhealthy.for.Sensitive.Groups.Days + Unhealthy.Days + Very.Unhealthy.Days + Hazardous.Days + Median.AQI + Days.CO + Days.NO2 + Days.Ozone + Days.PM2.5 + Value..Dollars. + factor(geo), data = data)
summary(mod2)
# moderate days, unhealthy for sensitive, very unhealthy, hazardous, median income, NE, SE, and W are statistically significant 

# checking multicollinearity again 
car::vif(mod2)
# looks like days ozone is colinear 

# redoing the model without days ozone 
mod3 <- lm(Deaths ~ Good.Days + Moderate.Days + Unhealthy.for.Sensitive.Groups.Days + Unhealthy.Days + Very.Unhealthy.Days + Hazardous.Days + Median.AQI + Days.CO + Days.NO2 + Days.PM2.5 + Value..Dollars. + factor(geo), data = data)
summary(mod3)
# moderate days, unhealthy for sensitive days, very unhealthy, hazardous, median income, NE, SE, and W are stat sig

# checking multicollinearity again 
car::vif(mod3)
# looks good

# looking for interactions to add to the final model 
add1(mod3, scope = .~. + .^2, test="F")

# sorting these interactions to put stat sig p values on top 
add1.test <- add1(mod3, scope = .~. + .^2, test="F")
add1.test[order(add1.test$`Pr(>F)`),]
# lots of interactions look significant, lets look at hazardous days and median income 
mod4 <- lm(Deaths ~ Good.Days + Moderate.Days + Unhealthy.for.Sensitive.Groups.Days + Unhealthy.Days + Very.Unhealthy.Days + Hazardous.Days * Value..Dollars. + Median.AQI + Days.CO + Days.NO2 + Days.PM2.5 + factor(geo), data = data)
summary(mod4)
# is SS but the effect is very low

# lets try unhealthy days and geographic region as the interaction 
mod5 <- lm(Deaths ~ Good.Days + Moderate.Days + Unhealthy.for.Sensitive.Groups.Days + Unhealthy.Days * factor(geo) + Very.Unhealthy.Days + Hazardous.Days + Value..Dollars. + Median.AQI + Days.CO + Days.NO2 + Days.PM2.5, data = data)
summary(mod5)
# looks like the interaction effect is SS for all regions and causes a huge difference
# this will be our final model 
final_reg_table <- stargazer(mod5, type = "html", title = "Regression Results",
                        align = TRUE, style = "qje", out = "LING_regression_table.html")
```

